name: 'Buildpack CI'
description: 'Automatically build and run unit tests with buildpacks for your app (a la Heroku) so that you can focus on building your app instead of thinking about how to configure CI to test the app.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'red'
