name: 'Buildpack Builds'
description: 'Easily run builds with minimal configuration efforts by using buildpacks a la Heroku'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'red'
